export const FETCH_SCHEDULES_REQUEST = "FETCH_SCHEDULES_REQUEST";
export const FETCH_SCHEDULES_SUCCESS = "FETCH_SCHEDULES_SUCCESS";
export const FETCH_SCHEDULES_FAILURE = "FETCH_SCHEDULES_FAILURE";

export const FETCH_MORE_SCHEDULES_REQUEST = "FETCH_MORE_SCHEDULES_REQUEST";
export const FETCH_MORE_SCHEDULES_SUCCESS = "FETCH_MORE_SCHEDULES_SUCCESS";
export const FETCH_MORE_SCHEDULES_FAILURE = "FETCH_MORE_SCHEDULES_FAILURE";

export const GET_SCHEDULE_REQUEST = "GET_SCHEDULE_REQUEST";
export const GET_SCHEDULE_SUCCESS = "GET_SCHEDULE_SUCCESS";
export const GET_SCHEDULE_FAILURE = "GET_SCHEDULE_FAILURE";
