export const billTypes = {
  FETCH_BILLS_REQUEST: "FETCH_BILLS_REQUEST",
  FETCH_BILLS_SUCCESS: "FETCH_BILLS_SUCCESS",
  FETCH_BILLS_FAILURE: "FETCH_BILLS_FAILURE",

  FETCH_MORE_BILLS_REQUEST: "FETCH_MORE_BILLS_REQUEST",
  FETCH_MORE_BILLS_SUCCESS: "FETCH_MORE_BILLS_SUCCESS",
  FETCH_MORE_BILLS_FAILURE: "FETCH_MORE_BILLS_FAILURE",

  GET_BILL_REQUEST: "GET_BILL_REQUEST",
  GET_BILL_SUCCESS: "GET_BILL_SUCCESS",
  GET_BILL_FAILURE: "GET_BILL_FAILURE",
};
