export const WELCOME_SCREEN = "TOGGLE_WELCOME_SCREEN";
export const RESET_STATE_KEY = "RESET_STATE_KEY";

export const OTP_REQUEST = "OTP_REQUEST";
export const OTP_SUCCESS = "OTP_SUCCESS";
export const OTP_FAILURE = "OTP_FAILURE";

export const CHECK_REQUEST = "USER_CHECK_REQUEST";
export const CHECK_SUCCESS = "USER_CHECK_SUCCESS";
export const CHECK_FAILURE = "USER_CHECK_FAILURE";

export const REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const REGISTER_FAILURE = "USER_REGISTER_FAILURE";

export const LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const LOGIN_FAILURE = "USER_LOGIN_FAILURE";

export const UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const UPDATE_FAILURE = "USER_UPDATE_FAILURE";

export const UPDATE_VERIFY_REQUEST = "USER_UPDATE_VERIFY_REQUEST";
export const UPDATE_VERIFY_SUCCESS = "USER_UPDATE_VERIFY_SUCCESS";
export const UPDATE_VERIFY_FAILURE = "USER_UPDATE_VERIFY_FAILURE";

export const LOGOUT = "USER_LOGOUT";

export const GET_USER = "USER_GET_CURRENT";
export const GET_REQUEST = "USER_GET_REQUEST";
export const GET_SUCCESS = "USER_GET_SUCCESS";
export const GET_FAILURE = "USER_GET_FAILURE";
