export const authTypes = {
  WELCOME_SCREEN: "TOGGLE_WELCOME_SCREEN",
  RESET_STATE_KEY: "RESET_STATE_KEY",

  OTP_REQUEST: "OTP_REQUEST",
  OTP_SUCCESS: "OTP_SUCCESS",
  OTP_FAILURE: "OTP_FAILURE",

  CHECK_REQUEST: "USER_CHECK_REQUEST",
  CHECK_SUCCESS: "USER_CHECK_SUCCESS",
  CHECK_FAILURE: "USER_CHECK_FAILURE",

  REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  REGISTER_FAILURE: "USER_REGISTER_FAILURE",

  LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  LOGIN_FAILURE: "USER_LOGIN_FAILURE",

  UPDATE_REQUEST: "USER_UPDATE_REQUEST",
  UPDATE_SUCCESS: "USER_UPDATE_SUCCESS",
  UPDATE_FAILURE: "USER_UPDATE_FAILURE",

  UPDATE_VERIFY_REQUEST: "USER_UPDATE_VERIFY_REQUEST",
  UPDATE_VERIFY_SUCCESS: "USER_UPDATE_VERIFY_SUCCESS",
  UPDATE_VERIFY_FAILURE: "USER_UPDATE_VERIFY_FAILURE",

  LOGOUT: "USER_LOGOUT",

  GET_USER: "USER_GET_CURRENT",
  GET_REQUEST: "USER_GET_REQUEST",
  GET_SUCCESS: "USER_GET_SUCCESS",
  GET_FAILURE: "USER_GET_FAILURE",
};
