export const FETCH_ANNOUNCEMENTS_REQUEST = "FETCH_ANNOUNCEMENTS_REQUEST";
export const FETCH_ANNOUNCEMENTS_SUCCESS = "FETCH_ANNOUNCEMENTS_SUCCESS";
export const FETCH_ANNOUNCEMENTS_FAILURE = "FETCH_ANNOUNCEMENTS_FAILURE";

export const FETCH_MORE_ANNOUNCEMENTS_REQUEST = "FETCH_MORE_ANNOUNCEMENTS_REQUEST";
export const FETCH_MORE_ANNOUNCEMENTS_SUCCESS = "FETCH_MORE_ANNOUNCEMENTS_SUCCESS";
export const FETCH_MORE_ANNOUNCEMENTS_FAILURE = "FETCH_MORE_ANNOUNCEMENTS_FAILURE";

export const GET_ANNOUNCEMENT_REQUEST = "GET_ANNOUNCEMENT_REQUEST";
export const GET_ANNOUNCEMENT_SUCCESS = "GET_ANNOUNCEMENT_SUCCESS";
export const GET_ANNOUNCEMENT_FAILURE = "GET_ANNOUNCEMENT_FAILURE";
