export const FETCH_BILLS_REQUEST = "FETCH_BILLS_REQUEST";
export const FETCH_BILLS_SUCCESS = "FETCH_BILLS_SUCCESS";
export const FETCH_BILLS_FAILURE = "FETCH_BILLS_FAILURE";

export const FETCH_MORE_BILLS_REQUEST = "FETCH_MORE_BILLS_REQUEST";
export const FETCH_MORE_BILLS_SUCCESS = "FETCH_MORE_BILLS_SUCCESS";
export const FETCH_MORE_BILLS_FAILURE = "FETCH_MORE_BILLS_FAILURE";

export const GET_BILL_REQUEST = "GET_BILL_REQUEST";
export const GET_BILL_SUCCESS = "GET_BILL_SUCCESS";
export const GET_BILL_FAILURE = "GET_BILL_FAILURE";
